# 卷积运算

In [1]:
import torch
# 设定一个输入 tensor
input = torch.tensor([[1,2,0,3,1],
                      [0,1,2,3,1],
                      [1,2,1,0,0],
                      [5,2,3,1,1],
                      [2,1,0,1,1]])
# 设定一个卷积核 kernel
kernel = torch.tensor([[1,2,1],
                       [0,1,0],
                       [2,1,0]])
print(f'input_shape: {input.shape}')
print(f'kernel_shape: {kernel.shape}')


input_shape: torch.Size([5, 5])
kernel_shape: torch.Size([3, 3])


由于 nn.covn2d 的运算是四维张量，需要对目前的 tensor 进行reshape

对图片卷积中四维的理解：每个维度分别对应
1. 每个 batch 里面图片的张数，即 batch_size
2. 每张图片的 channel 数，通常一张图片有 RGB 3个 channel
3. 每张图片的高
4. 每张图片的宽

In [2]:
input = torch.reshape(input, (1,1,5,5))
kernel = torch.reshape(kernel, (1,1,3,3))

卷积函数计算

In [3]:
import torch.nn.functional as F
output1 = F.conv2d(input=input, weight=kernel, bias=None, stride=1, padding=0)
output1

tensor([[[[10, 12, 12],
          [18, 16, 16],
          [13,  9,  3]]]])

In [4]:
output2 = F.conv2d(input=input, weight=kernel, bias=None, stride=2, padding=0)
output2

tensor([[[[10, 12],
          [13,  3]]]])

padding 的处理过程

padding=n 时，会在上下左右都添加n行或n列，默认填充值为0

In [5]:
output2 = F.conv2d(input=input, weight=kernel, bias=None, stride=1, padding=1)
output2

tensor([[[[ 1,  3,  4, 10,  8],
          [ 5, 10, 12, 12,  6],
          [ 7, 18, 16, 16,  8],
          [11, 13,  9,  3,  4],
          [14, 13,  9,  7,  4]]]])